scheme: http
keycloak-host: https://localhost:8443
username-claim: preferred_username
master-issuer: ${keycloak-host}/realms/master
bff-secret: change-me

gateway-uri: ${scheme}://localhost:${server.port}
management-console-api-uri: ${scheme}://localhost:7084
ui-host: https://localhost:4200

server:
  port: 7080
  shutdown: graceful
  ssl:
    enabled: false

spring:
  config:
    import:
    - optional:configtree:/workspace/config/
    - optional:configtree:/workspace/secret/
  lifecycle:
    timeout-per-shutdown-phase: 30s
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${master-issuer}
            user-name-attribute: ${username-claim}
        registration:
          egastro-bff:
            provider: keycloak
            client-id: egastro-bff
            client-secret: ${bff-secret}
            authorization-grant-type: authorization_code
            scope:
            - openid
            - profile
            - email
            - offline_access
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
      # Redirection from / to /ui/
      - id: home
        uri: ${gateway-uri}
        predicates:
        - Path=/
        filters:
        - RedirectTo=301,${gateway-uri}/ui/
      # Serve the Angular app through the gateway
      - id: ui
        uri: ${ui-host}
        predicates:
        - Path=/ui/**
      # Access the API with BFF pattern
      - id: bff
        uri: ${management-console-api-uri}
        predicates:
        - Path=/bff/v1/**
        filters:
        - TokenRelay=
        - SaveSession
        - StripPrefix=2

com:
  c4-soft:
    springaddons:
      oidc:
        # Global OAuth2 configuration
        ops:
        - iss: ${master-issuer}
          username-claim: ${username-claim}
          authorities:
          - path: $.realm_access.roles
          - path: $.resource_access.observability.roles
        client:
          client-uri: ${gateway-uri}
          security-matchers:
          - /bff/**
          - /login/**
          - /logout
          - /oauth2/**
          permit-all:
          - /bff/**
          - /login/**
          - /oauth2/**
          csrf: cookie-accessible-from-js
          post-login-redirect-path: /ui/
          post-logout-redirect-path: /ui/
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED
          cors:
          - allowed-origin-patterns: ${ui-host}
        # OAuth2 resource server configuration
        resourceserver:
          permit-all:
          - /error
          - /login-options
          - /ui/**
          - /v3/api-docs/**
          - /actuator/health/readiness
          - /actuator/health/liveness
          - /.well-known/**
          cors:
          - allowed-origin-patterns: ${ui-host}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        boot: INFO
    
---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    enabled: true

scheme: https