scheme: http
hostname: localhost
ingress-host: ${scheme}://${hostname}:7080
egastro-issuer: ${ingress-host}/auth/realms/egastro
master-issuer: ${ingress-host}/auth/realms/master
username-claim: sub
oauth2-clients-secret: change-me

management-console-api-uri: ${scheme}://${hostname}:7084

server:
  port: 7081
  shutdown: graceful
  ssl:
    enabled: false

spring:
  config:
    import:
    - optional:configtree:/workspace/config/
    - optional:configtree:/workspace/secret/
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  security:
    oauth2:
      client:
        provider:
          master:
            issuer-uri: ${master-issuer}
            user-name-attribute: ${username-claim}
          egastro:
            issuer-uri: ${egastro-issuer}
            user-name-attribute: ${username-claim}
        registration:
          egastro-admin-client:
            provider: master
            client-id: egastro-admin-client
            client-secret: ${admin-client-secret}
            authorization-grant-type: client_credentials
            scope:
            - openid
            - offline_access
          admin-console:
            provider: egastro
            client-id: admin-console
            client-secret: ${oauth2-clients-secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: ${ingress-host}/login/oauth2/code/admin-console
            scope:
            - openid
            - profile
            - email
            - offline_access
  cloud:
    gateway:
      routes:
      - id: bff
        uri: ${management-console-api-uri}
        predicates:
        - Path=/bff/v1/**
        filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - TokenRelay=
        - SaveSession
        - StripPrefix=2

com:
  c4-soft:
    springaddons:
      oidc:
        # Global OAuth2 configuration
        ops:
        - iss: ${egastro-issuer}
          username-claim: ${username-claim}
          authorities:
          - path: $.realm_access.roles
        - iss: ${master-issuer}
          username-claim: ${username-claim}
          authorities:
          - path: $.realm_access.roles
        client:
          client-uri: ${ingress-host}
          security-matchers:
          - /bff/**
          - /login/**
          - /logout
          - /oauth2/**
          - /client-registrations/**
          permit-all:
          - /bff/**
          - /login/**
          - /oauth2/**
          csrf: cookie-accessible-from-js
          post-login-redirect-host: ${ingress-host}
          post-login-redirect-path: /sushibach
          post-logout-redirect-host: ${ingress-host}
          post-logout-redirect-path: /sushibach
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED
          cors:
        # OAuth2 resource server configuration
        resourceserver:
          permit-all:
          - /error
          - /login-options
          - /admin-console/**
          - /sushibach/**
          - /burger-house/**
          - /auth/**
          - /v3/api-docs/**
          - /swagger-ui/**
          - /actuator/health/readiness
          - /actuator/health/liveness
          - /.well-known/**
          cors:

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO
        security: TRACE
        web: TRACE

egastro:
  keycloak:
    client-service:
      admin-api-uri: ${ingress-host}/auth/admin
      web-client-registration: egastro-admin-client
      default-secret: 
      realm: egastro
      provider: egastro
      redirectUris:
      - https://bravo-ch4mp.local:7080/*
      - https://bravo-ch4mp:7080/*
      - https://192.168.1.182:7080/*
      - https://localhost:7080/*
      - https://mc-ch4mp.local:7080/*
      - https://127.0.0.1:7080/*
      - https://10.0.2.2:7080/*
      - https://mc-ch4mp:7080/*
      - http://bravo-ch4mp.local:7080/*
      - http://bravo-ch4mp:7080/*
      - http://192.168.1.182:7080/*
      - http://localhost:7080/*
      - http://mc-ch4mp.local:7080/*
      - http://127.0.0.1:7080/*
      - http://10.0.2.2:7080/*
      - http://mc-ch4mp:7080/*
      magic-link-flow-id: change-me
      user-grants-mapper-conf:
        client-id: restaurants-employees-mapper
        client-secret: change-me
        token-endpoint: ${master-issuer}/protocol/openid-connect/token
        api-base-uri: ${management-console-api-uri}/users

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:egastro
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/egastro
    username: egastro
    password: change-me

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/egastro
    username: egastro
    password: change-me

---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    enabled: true

scheme: https