scheme: http
hostname: localhost
keycloak-host: https://${hostname}:8443
username-claim: sub
oauth2-clients-secret: change-me

gateway-uri: ${scheme}://${hostname}:${server.port}
management-console-api-uri: ${scheme}://${hostname}:7084

server:
  port: 7080
  shutdown: graceful
  ssl:
    enabled: false

spring:
  config:
    import:
    - optional:configtree:/workspace/config/
    - optional:configtree:/workspace/secret/
  lifecycle:
    timeout-per-shutdown-phase: 30s
  security:
    oauth2:
      client:
        provider:
          business:
            issuer-uri: ${keycloak-host}/realms/business
            user-name-attribute: ${username-claim}
          consumer:
            issuer-uri: ${keycloak-host}/realms/consumer
            user-name-attribute: ${username-claim}
        registration:
          admin-console:
            provider: business
            client-id: admin-console
            client-secret: ${oauth2-clients-secret}
            authorization-grant-type: authorization_code
            scope:
            - openid
            - profile
            - email
            - offline_access
          sushibach:
            provider: business
            client-id: sushibach
            client-secret: ${oauth2-clients-secret}
            authorization-grant-type: authorization_code
            scope:
            - openid
            - profile
            - email
            - offline_access
          burger-house:
            provider: business
            client-id: burger-house
            client-secret: ${oauth2-clients-secret}
            authorization-grant-type: authorization_code
            scope:
            - openid
            - profile
            - email
            - offline_access
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
      # Redirection from / to /ui/
      - id: home
        uri: ${gateway-uri}
        predicates:
        - Path=/
        filters:
        - RedirectTo=301,${gateway-uri}/admin-console/
      
      # Serve the Vue 3 frontends through the gateway
      - id: admin-console
        uri: ${scheme}://${hostname}:4200
        predicates:
        - Path=/admin-console/**
      - id: sushibach
        uri: ${scheme}://${hostname}:4201
        predicates:
        - Path=/sushibach/**
      - id: burger-house
        uri: ${scheme}://${hostname}:4202
        predicates:
        - Path=/burger-house/**
      
      # Proxy authorization-server
      - id: keycloak
        uri: ${keycloak-host}
        predicates:
        - Path=/realms/**
      - id: keycloak-resources
        uri: ${keycloak-host}
        predicates:
        - Path=/resources/2i2l7/**
      
      # Access the API with BFF pattern
      - id: bff
        uri: ${management-console-api-uri}
        predicates:
        - Path=/bff/v1/**
        filters:
        - TokenRelay=
        - SaveSession
        - StripPrefix=2

com:
  c4-soft:
    springaddons:
      oidc:
        # Global OAuth2 configuration
        ops:
        - iss: ${keycloak-host}/realms/master
          username-claim: ${username-claim}
          authorities:
          - path: $.realm_access.roles
        - iss: ${keycloak-host}/realms/business
          username-claim: ${username-claim}
          authorities:
          - path: $.realm_access.roles
        - iss: ${keycloak-host}/realms/consumer
          username-claim: ${username-claim}
          authorities:
          - path: $.realm_access.roles
        client:
          client-uri: ${gateway-uri}
          security-matchers:
          - /bff/**
          - /login/**
          - /logout
          - /oauth2/**
          permit-all:
          - /bff/**
          - /login/**
          - /oauth2/**
          csrf: cookie-accessible-from-js
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED
          cors:
          - allowed-origin-patterns: ${ui-host}
        # OAuth2 resource server configuration
        resourceserver:
          permit-all:
          - /error
          - /login-options
          - /admin-console/**
          - /sushibach/**
          - /burger-house/**
          - /realms/**
          - /resources/2i2l7/**
          - /v3/api-docs/**
          - /swagger-ui/**
          - /actuator/health/readiness
          - /actuator/health/liveness
          - /.well-known/**
          cors:
          - allowed-origin-patterns: ${ui-host}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
        boot: INFO
    
---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    enabled: true

scheme: https