scheme: http
hostname: localhost
egastro-issuer: ${scheme}://${hostname}:7080/auth/realms/egastro
master-issuer: ${scheme}://${hostname}:7080/auth/realms/master
admin-api: ${scheme}://${hostname}:7080/auth/admin
username-claim: sub
admin-client-secret: change-me

server:
  port: 7084
  error:
    include-message: always
  shutdown: graceful
  ssl:
    enabled: false

spring:
  config:
    import:
    - optional:configtree:/workspace/config/
    - optional:configtree:/workspace/secret/
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
  cloud:
    openfeign:
      client:
        config:
          keycloak-admin-realm:
            url: ${admin-api}/realms
          keycloak-admin-user:
            url: ${admin-api}/realms
      oauth2:
        enabled: true
        clientRegistrationId: egastro-admin-client
  security:
    oauth2:
      client:
        provider:
          master:
            issuer-uri: ${master-issuer}
        registration:
          egastro-admin-client:
            provider: master
            client-id: egastro-admin-client
            client-secret: ${admin-client-secret}
            authorization-grant-type: client_credentials
            scope:
            - openid
            - offline_access

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${master-issuer}
          username-claim: ${username-claim}
          authorities:
          - path: $.realm_access.roles
        - iss: ${egastro-issuer}
          username-claim: ${username-claim}
          authorities:
          - path: $.realm_access.roles
        resourceserver:
          permit-all:
          - "/error"
          - "/users/**"
          - "/realms/**"
          - "/actuator/health/readiness"
          - "/actuator/health/liveness"
          - "/v3/api-docs/**"
          - "/swagger-ui/**"
        
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        boot: INFO

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:egastro
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/egastro
    username: egastro
    password: change-me

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/egastro
    username: egastro
    password: change-me

---
server:
  ssl:
    enabled: true

spring:
  config:
    activate:
      on-profile: ssl

scheme: https